---
- name: Gather information about distribution
  ansible.builtin.setup:
    gather_subset:
      - "distribution"
  when: ansible_distribution is not defined

- name: Install Docker apt sources
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: "https://download.docker.com/linux/debian"
    signed_by: "https://download.docker.com/linux/debian/gpg"
    suites: ["{{ ansible_facts['distribution_release'] }}"]
    components: [stable]
    state: present
    enabled: "true"

- name: Install Docker
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: latest
    update_cache: "yes"

- name: Enable live restore
  when: docker_live_restore
  notify: "Restart docker"
  ansible.builtin.lineinfile:
    dest: "/etc/docker/daemon.json"
    create: true
    state: present
    mode: "0644"
    line: '{ "live-restore": true }'

- name: Create proxy network
  when: docker_create_proxy_network
  community.docker.docker_network:
    name: proxy
